/**
 * Curated authentic Indian itineraries for deterministic development and fallback.
 */

export const REALISTIC_VARANASI_ITINERARY = [
  {
    dayNumber: 1,
    title: 'The Sacred River & Ancient Ghats',
    date: 'DAY 01 · DAWN ON THE GANGES',
    weather: '24°C Morning Mist',
    endTime: '20:30',
    totalCost: 1150,
    totalTravelTime: 55,
    totalDistanceKm: 6.2,
    stops: [
      {
        attractionId: 'vns-1',
        name: 'Assi Ghat & Subah-e-Banaras',
        category: ['Spiritual', 'Ghat', 'Sunrise'],
        rating: 4.9,
        startTime: '05:30',
        duration: 90,
        cost: 0,
        description: 'Vedic chants, classical morning ragas, and watching the sunrise bathe the stone steps in gold.',
        openingHours: { open: '05:00', close: '22:00' },
        travelToNext: { distanceKm: 1.5, durationMinutes: 20 },
        coordinates: { lat: 25.2885, lng: 83.0068 },
        image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?q=80&w=1200&auto=format&fit=crop',
      },
      {
        attractionId: 'vns-2',
        name: 'Ram Bhandar Traditional Breakfast',
        category: ['Cuisine', 'Heritage Food'],
        rating: 4.8,
        startTime: '07:30',
        duration: 45,
        cost: 150,
        description: 'Authentic Banarasi kachori sabzi served on leaf plates with freshly fried jalebis in the narrow Thatheri bazaar.',
        openingHours: { open: '07:00', close: '11:00' },
        travelToNext: { distanceKm: 0.8, durationMinutes: 12 },
        coordinates: { lat: 25.3105, lng: 83.0112 },
      },
      {
        attractionId: 'vns-3',
        name: 'Kashi Vishwanath Corridor & Golden Temple',
        category: ['Heritage', 'Spiritual', 'Architecture'],
        rating: 4.9,
        startTime: '09:00',
        duration: 120,
        cost: 300,
        description: 'The monumental sacred corridor linking the river ghats directly to the ancient Jyotirlinga sanctum.',
        openingHours: { open: '04:00', close: '21:00' },
        travelToNext: { distanceKm: 1.2, durationMinutes: 15 },
        coordinates: { lat: 25.3109, lng: 83.0107 },
        image: 'https://images.unsplash.com/photo-1627894483216-2138af692e32?q=80&w=1200&auto=format&fit=crop',
      },
      {
        attractionId: 'vns-4',
        name: 'Manikarnika & Harishchandra Ghats Boat Ride',
        category: ['Culture', 'Boat Journey'],
        rating: 4.7,
        startTime: '15:30',
        duration: 90,
        cost: 450,
        description: 'Wooden rowing boat cruising past historical palace havelis, marigold flower markets, and timeless riverside life.',
        openingHours: { open: '06:00', close: '19:00' },
        travelToNext: { distanceKm: 0.5, durationMinutes: 10 },
        coordinates: { lat: 25.3113, lng: 83.0139 },
      },
      {
        attractionId: 'vns-5',
        name: 'Dashashwamedh Ghat Evening Maha Aarti',
        category: ['Ceremony', 'Spiritual Spectacle'],
        rating: 4.9,
        startTime: '18:15',
        duration: 90,
        cost: 250,
        description: 'Grand synchronized multi-tiered brass lamp ceremony performed by priests as floating oil diyas illuminate the river.',
        openingHours: { open: '18:00', close: '20:30' },
        travelToNext: null,
        coordinates: { lat: 25.3076, lng: 83.0104 },
        image: 'https://images.unsplash.com/photo-1571536802807-30451e3955d8?q=80&w=1200&auto=format&fit=crop',
      },
    ],
  },
  {
    dayNumber: 2,
    title: 'Buddhism at Sarnath & Master Silk Weavers',
    date: 'DAY 02 · DHARMA & TEXTILES',
    weather: '26°C Clear',
    endTime: '19:30',
    totalCost: 1400,
    totalTravelTime: 65,
    totalDistanceKm: 18.5,
    stops: [
      {
        attractionId: 'vns-6',
        name: 'Sarnath Deer Park & Dhamek Stupa',
        category: ['History', 'Buddhist Heritage', 'ASI Monument'],
        rating: 4.8,
        startTime: '08:30',
        duration: 150,
        cost: 300,
        description: 'Where the Buddha delivered his first sermon after enlightenment. Massive 5th-century cylindrical stone stupa.',
        openingHours: { open: '08:00', close: '17:00' },
        travelToNext: { distanceKm: 0.4, durationMinutes: 5 },
        coordinates: { lat: 25.3811, lng: 83.0214 },
        image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?q=80&w=1200&auto=format&fit=crop',
      },
      {
        attractionId: 'vns-7',
        name: 'Sarnath Archaeological Museum',
        category: ['Museum', 'Sculpture'],
        rating: 4.8,
        startTime: '11:15',
        duration: 75,
        cost: 50,
        description: 'Houses the famous Lion Capital of Ashoka (National Emblem of India) sculpted in polished Chunar sandstone.',
        openingHours: { open: '09:00', close: '17:00' },
        travelToNext: { distanceKm: 12.0, durationMinutes: 30 },
        coordinates: { lat: 25.3789, lng: 83.0242 },
      },
      {
        attractionId: 'vns-8',
        name: 'Peeli Kothi Artisan Silk Weaving Guild',
        category: ['Craft', 'Textiles', 'Culture'],
        rating: 4.7,
        startTime: '14:30',
        duration: 90,
        cost: 0,
        description: 'Generations of master Muslim weavers working pit looms to handcraft authentic Banarasi zari silk sarees.',
        openingHours: { open: '10:00', close: '18:30' },
        travelToNext: { distanceKm: 4.5, durationMinutes: 20 },
        coordinates: { lat: 25.3255, lng: 83.0042 },
      },
      {
        attractionId: 'vns-9',
        name: 'Blue Lassi Shop & Godowlia Chowk Walk',
        category: ['Local Food', 'Old City'],
        rating: 4.6,
        startTime: '16:30',
        duration: 60,
        cost: 200,
        description: 'Creamy clay-pot curd lassi topped with pomegranate, crushed pistachios, and rabri.',
        openingHours: { open: '09:00', close: '22:00' },
        travelToNext: null,
        coordinates: { lat: 25.3094, lng: 83.0089 },
      },
    ],
  },
  {
    dayNumber: 3,
    title: 'Fortress across the Ganges & Forest Ashrams',
    date: 'DAY 03 · HERITAGE OUTSKIRTS',
    weather: '27°C Sunny',
    endTime: '18:00',
    totalCost: 950,
    totalTravelTime: 50,
    totalDistanceKm: 14.0,
    stops: [
      {
        attractionId: 'vns-10',
        name: 'Ramnagar Fort & Royal Vintage Museum',
        category: ['Fort', 'Royal Heritage'],
        rating: 4.5,
        startTime: '09:30',
        duration: 120,
        cost: 200,
        description: '18th-century cream sandstone fort on the eastern bank of the Ganges, featuring royal palanquins and armory.',
        openingHours: { open: '10:00', close: '17:00' },
        travelToNext: { distanceKm: 6.0, durationMinutes: 20 },
        coordinates: { lat: 25.2678, lng: 83.0251 },
      },
      {
        attractionId: 'vns-11',
        name: 'BHU Vishwanath Temple & Green Campus Walk',
        category: ['Architecture', 'Peaceful Campus'],
        rating: 4.7,
        startTime: '13:00',
        duration: 90,
        cost: 0,
        description: 'Towering white marble replica temple situated within the sprawling, tree-lined Banaras Hindu University sanctuary.',
        openingHours: { open: '04:00', close: '21:00' },
        travelToNext: null,
        coordinates: { lat: 25.2657, lng: 82.9904 },
      },
    ],
  },
];

export const REALISTIC_JAIPUR_ITINERARY = [
  {
    dayNumber: 1,
    title: 'The Hill Fortresses of Amber & Nahargarh',
    date: 'DAY 01 · RAJPUT FORTRESSES',
    weather: '25°C Dry & Pleasant',
    endTime: '19:00',
    totalCost: 1650,
    totalTravelTime: 60,
    totalDistanceKm: 24.0,
    stops: [
      {
        attractionId: 'jai-1',
        name: 'Amber Palace (Amer Fort)',
        category: ['Fort', 'Royal Heritage', 'UNESCO'],
        rating: 4.8,
        startTime: '08:30',
        duration: 150,
        cost: 500,
        description: 'Opulent Rajput-Mughal fortress overlooking Maota Lake, famous for Sheesh Mahal (hall of mirrors).',
        openingHours: { open: '08:00', close: '17:30' },
        travelToNext: { distanceKm: 1.5, durationMinutes: 10 },
        coordinates: { lat: 26.9855, lng: 75.8513 },
        image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?q=80&w=1200&auto=format&fit=crop',
      },
      {
        attractionId: 'jai-2',
        name: 'Panna Meena ka Kund Stepwell',
        category: ['Stepwell', 'Architecture', 'Geometric'],
        rating: 4.6,
        startTime: '11:15',
        duration: 45,
        cost: 0,
        description: '16th-century geometric stepwell with interlocking criss-cross yellow sandstone steps.',
        openingHours: { open: '07:00', close: '18:00' },
        travelToNext: { distanceKm: 8.0, durationMinutes: 20 },
        coordinates: { lat: 26.9877, lng: 75.8569 },
      },
      {
        attractionId: 'jai-3',
        name: 'Jal Mahal (Water Palace Promenade)',
        category: ['Palace', 'Lake', 'Viewpoint'],
        rating: 4.5,
        startTime: '13:00',
        duration: 45,
        cost: 0,
        description: 'Floating red sandstone palace submerged in Man Sagar Lake framed by the rugged Aravalli hills.',
        openingHours: { open: '06:00', close: '22:00' },
        travelToNext: { distanceKm: 10.0, durationMinutes: 25 },
        coordinates: { lat: 26.9534, lng: 75.8462 },
      },
      {
        attractionId: 'jai-4',
        name: 'Nahargarh Fort & Sunset Viewpoint',
        category: ['Fort', 'Sunset', 'Panoramic View'],
        rating: 4.7,
        startTime: '16:30',
        duration: 120,
        cost: 200,
        description: 'Historic defense ramparts along the cliff edge offering panoramic sunset views over the entire Pink City.',
        openingHours: { open: '10:00', close: '17:30' },
        travelToNext: null,
        coordinates: { lat: 26.9373, lng: 75.8155 },
        image: 'https://images.unsplash.com/photo-1606293926075-69a00dbfde81?q=80&w=1200&auto=format&fit=crop',
      },
    ],
  },
  {
    dayNumber: 2,
    title: 'The Walled Pink City, Observatories & Bazaars',
    date: 'DAY 02 · OLD CITY & BAZAARS',
    weather: '26°C Clear',
    endTime: '20:00',
    totalCost: 1950,
    totalTravelTime: 35,
    totalDistanceKm: 7.5,
    stops: [
      {
        attractionId: 'jai-5',
        name: 'Hawa Mahal (Palace of Winds)',
        category: ['Monument', 'Pink Sandstone', 'History'],
        rating: 4.7,
        startTime: '08:30',
        duration: 60,
        cost: 200,
        description: '953 carved sandstone windows capturing natural desert breezes in the heart of the walled city.',
        openingHours: { open: '09:00', close: '16:30' },
        travelToNext: { distanceKm: 0.6, durationMinutes: 8 },
        coordinates: { lat: 26.9239, lng: 75.8267 },
        image: 'https://images.unsplash.com/photo-1609840114035-3c981b782dfe?q=80&w=1200&auto=format&fit=crop',
      },
      {
        attractionId: 'jai-6',
        name: 'City Palace Complex & Courtyards',
        category: ['Palace', 'Museum', 'Courtyards'],
        rating: 4.7,
        startTime: '10:00',
        duration: 120,
        cost: 700,
        description: 'Seat of the Maharaja of Jaipur featuring Peacock Gate courtyards and royal textile collections.',
        openingHours: { open: '09:30', close: '17:00' },
        travelToNext: { distanceKm: 0.3, durationMinutes: 5 },
        coordinates: { lat: 26.9258, lng: 75.8236 },
      },
      {
        attractionId: 'jai-7',
        name: 'Jantar Mantar Royal Observatory',
        category: ['UNESCO', 'Science', 'Architecture'],
        rating: 4.6,
        startTime: '13:00',
        duration: 75,
        cost: 200,
        description: 'World’s largest stone sundial and nineteen architectural astronomical instruments built in 1734.',
        openingHours: { open: '09:00', close: '17:00' },
        travelToNext: { distanceKm: 1.2, durationMinutes: 12 },
        coordinates: { lat: 26.9248, lng: 75.8246 },
      },
      {
        attractionId: 'jai-8',
        name: 'Bapu Bazaar & Johari Bazaar Craft Walk',
        category: ['Shopping', 'Local Craft', 'Textiles'],
        rating: 4.6,
        startTime: '16:00',
        duration: 120,
        cost: 0,
        description: 'Exploring block-printed cottons, blue pottery, and authentic kachoris at Rawat Mishtan Bhandar.',
        openingHours: { open: '11:00', close: '21:00' },
        travelToNext: null,
        coordinates: { lat: 26.9189, lng: 75.8238 },
      },
    ],
  },
  {
    dayNumber: 3,
    title: 'Albert Hall Museum & Patrika Gate',
    date: 'DAY 03 · MODERN ARCHITECTURE',
    weather: '26°C Clear',
    endTime: '18:00',
    totalCost: 1200,
    totalTravelTime: 40,
    totalDistanceKm: 12.0,
    stops: [
      {
        attractionId: 'jai-9',
        name: 'Albert Hall State Museum',
        category: ['Museum', 'Indo-Saracenic Architecture'],
        rating: 4.6,
        startTime: '09:30',
        duration: 120,
        cost: 300,
        description: 'Finest example of Indo-Saracenic architecture in Rajasthan, surrounded by Ram Niwas Garden.',
        openingHours: { open: '09:00', close: '17:00' },
        travelToNext: { distanceKm: 8.5, durationMinutes: 20 },
        coordinates: { lat: 26.9116, lng: 75.8195 },
      },
      {
        attractionId: 'jai-10',
        name: 'Patrika Gate at Jawahar Circle',
        category: ['Architecture', 'Photography', 'Art'],
        rating: 4.7,
        startTime: '14:00',
        duration: 60,
        cost: 0,
        description: 'Stunning hand-painted ceremonial gateway depicting Rajasthan’s royal dynasties, wars, and folk art.',
        openingHours: { open: '06:00', close: '21:00' },
        travelToNext: null,
        coordinates: { lat: 26.8528, lng: 75.8058 },
      },
    ],
  },
];

export const REALISTIC_KERALA_ITINERARY = [
  {
    dayNumber: 1,
    title: 'Alleppey Canals & Private Kettuvallam Cruise',
    date: 'DAY 01 · SLOW BACKWATERS',
    weather: '28°C Tropical Breeze',
    endTime: '19:30',
    totalCost: 4800,
    totalTravelTime: 45,
    totalDistanceKm: 15.0,
    stops: [
      {
        attractionId: 'ker-1',
        name: 'Punnamada Jetty Houseboat Embarkation',
        category: ['Backwaters', 'Houseboat Cruise'],
        rating: 4.9,
        startTime: '10:00',
        duration: 240,
        cost: 4000,
        description: 'Cruising through narrow, palm-fringed lagoons and watching local canoe vendors and coir factories.',
        openingHours: { open: '08:00', close: '18:00' },
        travelToNext: { distanceKm: 4.0, durationMinutes: 15 },
        coordinates: { lat: 9.4981, lng: 76.3388 },
        image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
      },
      {
        attractionId: 'ker-2',
        name: 'Traditional Karimeen Pollichathu Lunch',
        category: ['Cuisine', 'Banana Leaf Feast'],
        rating: 4.8,
        startTime: '14:30',
        duration: 60,
        cost: 800,
        description: 'Locally caught Pearl Spot fish pan-fried with shallots, crushed pepper, and coconut milk.',
        openingHours: { open: '12:00', close: '16:00' },
        travelToNext: { distanceKm: 12.0, durationMinutes: 25 },
        coordinates: { lat: 9.5102, lng: 76.3456 },
      },
      {
        attractionId: 'ker-3',
        name: 'Marari Beach Sunset Promenade',
        category: ['Coast', 'Sunset'],
        rating: 4.7,
        startTime: '17:30',
        duration: 90,
        cost: 0,
        description: 'Peaceful white-sand fishing shoreline shaded by continuous groves of coconut palms.',
        openingHours: { open: '00:00', close: '23:59' },
        travelToNext: null,
        coordinates: { lat: 9.6012, lng: 76.2974 },
      },
    ],
  },
  {
    dayNumber: 2,
    title: 'Munnar High-Altitude Tea Estates & Mist',
    date: 'DAY 02 · CARDAMOM HILLS',
    weather: '18°C Misty',
    endTime: '18:30',
    totalCost: 1500,
    totalTravelTime: 90,
    totalDistanceKm: 35.0,
    stops: [
      {
        attractionId: 'ker-4',
        name: 'KDHP Tea Plantation & CTC Processing Museum',
        category: ['Tea Estate', 'History', 'Tasting'],
        rating: 4.8,
        startTime: '09:00',
        duration: 120,
        cost: 250,
        description: 'Walking through emerald green tea terraces, hand-picking fresh tips and touring 19th-century British machinery.',
        openingHours: { open: '09:00', close: '17:00' },
        travelToNext: { distanceKm: 12.0, durationMinutes: 30 },
        coordinates: { lat: 10.0889, lng: 77.0595 },
        image: 'https://images.unsplash.com/photo-1590766940554-634a7ed41450?q=80&w=1200&auto=format&fit=crop',
      },
      {
        attractionId: 'ker-5',
        name: 'Eravikulam National Park (Rajamalai Viewpoint)',
        category: ['Wildlife', 'High Peak', 'Nilgiri Tahr'],
        rating: 4.7,
        startTime: '13:00',
        duration: 150,
        cost: 400,
        description: 'Rolling shola-grassland sanctuary home to the endangered mountain goat, framed by Anamudi (South India’s highest peak).',
        openingHours: { open: '07:30', close: '16:00' },
        travelToNext: null,
        coordinates: { lat: 10.1518, lng: 77.0608 },
      },
    ],
  },
];

export const REALISTIC_UDAIPUR_ITINERARY = [
  {
    dayNumber: 1,
    title: 'The Mewar Royal Palaces & Pichola Waterway',
    date: 'DAY 01 · LAKE CAPITAL',
    weather: '26°C Clear',
    endTime: '19:30',
    totalCost: 1850,
    totalTravelTime: 40,
    totalDistanceKm: 8.5,
    stops: [
      {
        attractionId: 'udr-1',
        name: 'Udaipur City Palace Complex',
        category: ['Palace', 'Mewar Heritage', 'Architecture'],
        rating: 4.8,
        startTime: '09:00',
        duration: 180,
        cost: 400,
        description: 'Rajasthan’s largest palace complex, built over 400 years with inlaid colored glass, mirror mosaics, and marble balconies.',
        openingHours: { open: '09:00', close: '17:30' },
        travelToNext: { distanceKm: 0.5, durationMinutes: 10 },
        coordinates: { lat: 24.5764, lng: 73.6835 },
        image: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?q=80&w=1200&auto=format&fit=crop',
      },
      {
        attractionId: 'udr-2',
        name: 'Lake Pichola Sunset Boat to Jag Mandir',
        category: ['Boat Cruise', 'Island Palace', 'Sunset'],
        rating: 4.9,
        startTime: '16:00',
        duration: 90,
        cost: 650,
        description: 'Cruise past the floating Lake Palace (Taj Lake Palace) to the 17th-century island sanctuary of Jag Mandir.',
        openingHours: { open: '09:00', close: '18:30' },
        travelToNext: { distanceKm: 0.8, durationMinutes: 15 },
        coordinates: { lat: 24.5676, lng: 73.6781 },
      },
      {
        attractionId: 'udr-3',
        name: 'Bagore Ki Haveli Dharohar Folk Dance',
        category: ['Folk Performance', 'Puppetry', 'Haveli'],
        rating: 4.8,
        startTime: '19:00',
        duration: 75,
        cost: 150,
        description: 'Traditional Rajasthani Chari and Bhavai dance performed by women balancing ten brass pots on their heads.',
        openingHours: { open: '10:00', close: '20:00' },
        travelToNext: null,
        coordinates: { lat: 24.5796, lng: 73.6806 },
      },
    ],
  },
];

export const REALISTIC_LADAKH_ITINERARY = [
  {
    dayNumber: 1,
    title: 'Indus Valley Monasteries & Royal Citadel',
    date: 'DAY 01 · CLIFF MONASTERIES',
    weather: '16°C Crisp Himalayan Sun',
    endTime: '18:00',
    totalCost: 1200,
    totalTravelTime: 85,
    totalDistanceKm: 42.0,
    stops: [
      {
        attractionId: 'ldk-1',
        name: 'Thiksey Monastery (Mini Potala)',
        category: ['Tibetan Buddhist', 'Monastery', 'Chanting'],
        rating: 4.9,
        startTime: '06:30',
        duration: 120,
        cost: 100,
        description: '12-storey hilltop monastic complex housing the serene 49-foot Maitreya (Future Buddha) statue.',
        openingHours: { open: '06:00', close: '18:00' },
        travelToNext: { distanceKm: 18.0, durationMinutes: 30 },
        coordinates: { lat: 34.0567, lng: 77.6667 },
        image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?q=80&w=1200&auto=format&fit=crop',
      },
      {
        attractionId: 'ldk-2',
        name: 'Shanti Stupa Sunset Panorama',
        category: ['Stupa', 'Viewpoint', 'Peace'],
        rating: 4.8,
        startTime: '16:30',
        duration: 90,
        cost: 0,
        description: 'Overlooking Leh valley, the ancient nine-storey Leh Palace, and the snow peaks of Stok Kangri range.',
        openingHours: { open: '05:00', close: '21:00' },
        travelToNext: null,
        coordinates: { lat: 34.1729, lng: 77.5744 },
      },
    ],
  },
];

/**
 * Universal resolver: Returns the authentic itinerary matching whatever Indian destination was selected!
 */
export const getItineraryForDestination = (destination = '') => {
  const d = (destination || '').toLowerCase();

  if (d.includes('jaipur') || d.includes('amer') || d.includes('pink city') || d.includes('rajasthan')) {
    return REALISTIC_JAIPUR_ITINERARY;
  }
  if (d.includes('kerala') || d.includes('munnar') || d.includes('alleppey') || d.includes('kochi') || d.includes('alappuzha')) {
    return REALISTIC_KERALA_ITINERARY;
  }
  if (d.includes('udaipur') || d.includes('pichola') || d.includes('mewar')) {
    return REALISTIC_UDAIPUR_ITINERARY;
  }
  if (d.includes('ladakh') || d.includes('leh') || d.includes('nubra') || d.includes('pangong')) {
    return REALISTIC_LADAKH_ITINERARY;
  }
  if (d.includes('varanasi') || d.includes('banaras') || d.includes('kashi') || d.includes('ganges')) {
    return REALISTIC_VARANASI_ITINERARY;
  }

  // If none matched, default to Jaipur (NOT Banaras!)
  return REALISTIC_JAIPUR_ITINERARY;
};

export const REALISTIC_PARIS_ITINERARY = REALISTIC_JAIPUR_ITINERARY; // Backward-compatible alias
export default REALISTIC_JAIPUR_ITINERARY;
