export const REALISTIC_PARIS_ITINERARY = [
  {
    dayNumber: 1,
    title: 'Historic Core & Royal Heritage',
    endTime: '18:30',
    totalCost: 2750,
    totalTravelTime: 45,
    totalDistanceKm: 2.5,
    stops: [
      {
        attractionId: 'stop-1',
        name: 'Louvre Museum',
        attraction: 'Louvre Museum',
        category: ['History', 'Art'],
        rating: 4.8,
        startTime: '09:00',
        duration: 150,
        cost: 1800,
        openingHours: { open: '09:00', close: '18:00' },
        travelToNext: { distanceKm: 1.2, durationMinutes: 18 },
        coordinates: { lat: 48.8606, lng: 2.3376 },
      },
      {
        attractionId: 'stop-2',
        name: 'Palais-Royal Gardens',
        attraction: 'Palais-Royal Gardens',
        category: ['Nature', 'Parks'],
        rating: 4.6,
        startTime: '12:00',
        duration: 60,
        cost: 0,
        openingHours: { open: '08:30', close: '20:30' },
        travelToNext: { distanceKm: 0.8, durationMinutes: 10 },
        coordinates: { lat: 48.8648, lng: 2.3378 },
      },
      {
        attractionId: 'stop-3',
        name: 'Café Lunch & Sainte-Chapelle',
        attraction: 'Sainte-Chapelle',
        category: ['Architecture'],
        rating: 4.7,
        startTime: '13:30',
        duration: 75,
        cost: 950,
        openingHours: { open: '09:00', close: '17:00' },
        travelToNext: { distanceKm: 0.5, durationMinutes: 7 },
        coordinates: { lat: 48.8554, lng: 2.345 },
      },
      {
        attractionId: 'stop-4',
        name: 'Notre-Dame Cathedral Parvis',
        attraction: 'Notre-Dame Cathedral',
        category: ['History', 'Culture'],
        rating: 4.8,
        startTime: '15:00',
        duration: 90,
        cost: 0,
        openingHours: { open: '08:00', close: '18:45' },
        travelToNext: null,
        coordinates: { lat: 48.8529, lng: 2.3499 },
      },
    ],
  },
  {
    dayNumber: 2,
    title: 'Historic Paris & River Monuments',
    endTime: '19:00',
    totalCost: 3200,
    totalTravelTime: 42,
    totalDistanceKm: 2.8,
    stops: [
      {
        attractionId: 'stop-5',
        name: 'Musée d’Orsay',
        attraction: 'Musée d’Orsay',
        category: ['Art', 'Museum'],
        rating: 4.8,
        startTime: '09:30',
        duration: 120,
        cost: 1600,
        openingHours: { open: '09:30', close: '18:00' },
        travelToNext: { distanceKm: 1.1, durationMinutes: 15 },
        coordinates: { lat: 48.8599, lng: 2.3265 },
      },
      {
        attractionId: 'stop-6',
        name: 'Tuileries Garden Stroll',
        attraction: 'Tuileries Garden',
        category: ['Nature', 'Parks'],
        rating: 4.6,
        startTime: '12:00',
        duration: 60,
        cost: 0,
        openingHours: { open: '07:00', close: '21:00' },
        travelToNext: { distanceKm: 1.4, durationMinutes: 18 },
        coordinates: { lat: 48.8638, lng: 2.3275 },
      },
      {
        attractionId: 'stop-7',
        name: 'Place de la Concorde & Tea',
        attraction: 'Place de la Concorde',
        category: ['Food & Dining'],
        rating: 4.5,
        startTime: '13:30',
        duration: 75,
        cost: 1600,
        openingHours: { open: '09:00', close: '20:00' },
        travelToNext: null,
        coordinates: { lat: 48.8656, lng: 2.3212 },
      },
    ],
  },
  {
    dayNumber: 3,
    title: 'Iconic Landmarks & River Views',
    endTime: '20:30',
    totalCost: 3400,
    totalTravelTime: 52,
    totalDistanceKm: 3.5,
    stops: [
      {
        attractionId: 'stop-8',
        name: 'Eiffel Tower Summit',
        attraction: 'Eiffel Tower',
        category: ['Architecture', 'Monument'],
        rating: 4.7,
        startTime: '09:00',
        duration: 120,
        cost: 2600,
        openingHours: { open: '09:00', close: '23:45' },
        travelToNext: { distanceKm: 0.9, durationMinutes: 12 },
        coordinates: { lat: 48.8584, lng: 2.2945 },
      },
      {
        attractionId: 'stop-9',
        name: 'Champ de Mars Garden Picnic',
        attraction: 'Champ de Mars',
        category: ['Nature'],
        rating: 4.6,
        startTime: '11:30',
        duration: 60,
        cost: 800,
        openingHours: { open: '00:00', close: '23:59' },
        travelToNext: { distanceKm: 1.3, durationMinutes: 18 },
        coordinates: { lat: 48.8556, lng: 2.2986 },
      },
      {
        attractionId: 'stop-10',
        name: 'Musée Rodin Sculptures',
        attraction: 'Musée Rodin',
        category: ['Art & Sculpture'],
        rating: 4.7,
        startTime: '13:30',
        duration: 90,
        cost: 0,
        openingHours: { open: '10:00', close: '18:30' },
        travelToNext: null,
        coordinates: { lat: 48.8553, lng: 2.3158 },
      },
    ],
  },
];
